#!/bin/bash
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
# MemFabric_Hybrid is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
#
# build_ops_run.sh - Build hybm ops (AICPU kernel) standalone and produce .run package.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OPS_SRC_DIR="${PROJECT_ROOT}/src/hybm/ops"

# Defaults
BUILD_DIR="${PROJECT_ROOT}/build/hybm_ops"
OUTPUT_DIR="${PROJECT_ROOT}/output"
BUILD_MODE="RELEASE"
JOBS=""
CLEAN=0

show_help() {
    cat <<EOF
Usage: $0 [options]

Build hybm ops (AICPU kernel) standalone and produce .run package.

Options:
  --build-dir <dir>    Build directory (default: ${PROJECT_ROOT}/build/hybm_ops)
  --output-dir <dir>   Output directory (default: ${PROJECT_ROOT}/output)
  --build-mode <mode>  Build mode: RELEASE, DEBUG (default: RELEASE)
  --clean              Clean build directory before building
  -j, --jobs <N>       Parallel build jobs (default: automatic)
  -h, --help           Show this help message

Environment variables:
  ASCEND_HOME_PATH     Path to CANN installation (for cross-compiler and headers)

Examples:
  $0
  $0 --build-mode DEBUG --clean
  $0 --build-dir /tmp/build_ops --output-dir /tmp/output -j 8
EOF
}

# ---- Parse arguments ----
while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-dir)
            BUILD_DIR="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --build-mode)
            BUILD_MODE="$2"
            shift 2
            ;;
        --clean)
            CLEAN=1
            shift
            ;;
        -j|--jobs)
            JOBS="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Error: Unknown argument: $1" >&2
            show_help >&2
            exit 1
            ;;
    esac
done

# Validate build mode
BUILD_MODE_UPPER="$(echo "${BUILD_MODE}" | tr '[:lower:]' '[:upper:]')"
if [[ "${BUILD_MODE_UPPER}" != "RELEASE" && "${BUILD_MODE_UPPER}" != "DEBUG" ]]; then
    echo "Error: BUILD_MODE must be RELEASE or DEBUG, got: ${BUILD_MODE}" >&2
    exit 1
fi

echo "============================================"
echo " hybm ops standalone build"
echo "============================================"
echo " PROJECT_ROOT      = ${PROJECT_ROOT}"
echo " OPS_SRC_DIR       = ${OPS_SRC_DIR}"
echo " BUILD_DIR         = ${BUILD_DIR}"
echo " OUTPUT_DIR        = ${OUTPUT_DIR}"
echo " BUILD_MODE        = ${BUILD_MODE_UPPER}"
echo " CLEAN             = ${CLEAN}"
echo " ASCEND_HOME_PATH  = ${ASCEND_HOME_PATH:-<not set>}"
echo "============================================"

AICPU_KERNEL_SOURCES="${OPS_SRC_DIR}/hybm_kernel/hybm_batch_transfer.cc;"
AICPU_KERNEL_SOURCES+="${PROJECT_ROOT}/src/acc_offload/csrc/operators/aicpu/hybm_aggregate_urma_demo.cc;"
AICPU_KERNEL_SOURCES+="${PROJECT_ROOT}/src/acc_offload/csrc/operators/aicpu/hybm_batch_copy.cc"

# ---- Clean if requested ----
if [[ ${CLEAN} -eq 1 && -d "${BUILD_DIR}" ]]; then
    echo "Cleaning build directory: ${BUILD_DIR}"
    rm -rf "${BUILD_DIR}"
fi

# ---- Configure ----
cmake_opts=(
    -S "${OPS_SRC_DIR}"
    -B "${BUILD_DIR}"
    -DHYBM_KERNEL_PROJECT_ROOT="${PROJECT_ROOT}"
    -DTARGET_INSTALL_DIR="${OUTPUT_DIR}"
    -DPROJECT_HYBM_SRC_BASE="${PROJECT_ROOT}/src/hybm"
    -DPROJECT_ACC_OFFLOAD_SRC_BASE="${PROJECT_ROOT}/src/acc_offload"
    -DPROJECT_UTIL_SRC_BASE="${PROJECT_ROOT}/src/util/csrc"
    -DAICPU_KERNEL_SRC="${AICPU_KERNEL_SOURCES}"
    -DCMAKE_BUILD_TYPE="${BUILD_MODE_UPPER}"
)

if [[ -n "${ASCEND_HOME_PATH:-}" ]]; then
    cmake_opts+=(-DASCEND_HOME_PATH="${ASCEND_HOME_PATH}")
fi

echo ""
echo "--- Running cmake configure ---"
cmake "${cmake_opts[@]}"

# ---- Build ----
build_args=(
    --build "${BUILD_DIR}"
    --target install
)
if [[ -n "${JOBS}" ]]; then
    build_args+=(--parallel "${JOBS}")
fi

echo ""
echo "--- Building and installing ---"
cmake "${build_args[@]}"

# ---- Generate cann_hybm_kernel_version ----
echo ""
echo "--- Generating cann_hybm_kernel_version ---"
KERNEL_VER_DIR="${OUTPUT_DIR}/hybm/aicpu_kernel"
KERNEL_VER_FILE="${KERNEL_VER_DIR}/cann_hybm_kernel_version"

mkdir -p "${KERNEL_VER_DIR}"
# Match format generated by script/build.sh: multi-line with version and git commit
MF_VERSION="$(cat "${PROJECT_ROOT}/VERSION" 2>/dev/null | tr -d '[:space:]' || echo "1.0.0")"
GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || true)"
{
  echo "mf version info:"
  echo "mf version: ${MF_VERSION}"
  echo "git: ${GIT_COMMIT}"
} > "${KERNEL_VER_FILE}"
echo "Generated ${KERNEL_VER_FILE}"
echo "  mf version: ${MF_VERSION}"
echo "  git: ${GIT_COMMIT}"

# ---- Verify required artifacts exist before packing ----
echo ""
echo "--- Checking artifacts ---"
ARTIFACTS_PRESENT=1
for f in cann-hybm-compat.tar.gz libcann_hybm_kernel.json install.sh cann_hybm_kernel_version; do
    if [[ ! -f "${KERNEL_VER_DIR}/${f}" ]]; then
        echo "ERROR: Missing artifact: ${KERNEL_VER_DIR}/${f}" >&2
        ARTIFACTS_PRESENT=0
    else
        echo "  OK: ${KERNEL_VER_DIR}/${f}"
    fi
done

if [[ ${ARTIFACTS_PRESENT} -eq 0 ]]; then
    echo "ERROR: Some artifacts are missing, cannot create .run package." >&2
    exit 1
fi

# ---- Create .run package ----
echo ""
echo "--- Creating .run package ---"

# make_kernel_run.sh hardcodes default output path; sync artifacts if needed
DEFAULT_KERNEL_DIR="${PROJECT_ROOT}/output/hybm/aicpu_kernel"
if [[ "${OUTPUT_DIR}" != "${PROJECT_ROOT}/output" ]]; then
    echo "Custom output dir (${OUTPUT_DIR}) differs from default."
    echo "Syncing artifacts to default path for make_kernel_run.sh ..."
    mkdir -p "${DEFAULT_KERNEL_DIR}"
    for f in cann-hybm-compat.tar.gz libcann_hybm_kernel.json install.sh cann_hybm_kernel_version; do
        if [[ -f "${KERNEL_VER_DIR}/${f}" ]]; then
            cp "${KERNEL_VER_DIR}/${f}" "${DEFAULT_KERNEL_DIR}/${f}"
            echo "  Copied: ${f}"
        fi
    done
fi

bash "${PROJECT_ROOT}/script/kernel/make_kernel_run.sh"

RUN_FILE="${PROJECT_ROOT}/output/memfabric_hybrid_aicpu_kernel.run"
if [[ -f "${RUN_FILE}" ]]; then
    echo ""
    echo "============================================"
    echo " SUCCESS: .run package created"
    echo "   ${RUN_FILE}"
    echo "============================================"
else
    echo ""
    echo "ERROR: .run package not found at expected path: ${RUN_FILE}" >&2
    exit 1
fi
